// src/components/Navbar.vue
<template>
    <nav class="w-full">
        <div class="mx-auto py-6 flex justify-center">
            <ul
                class="flex space-x-4 bg-white/20 backdrop-blur-2xl px-4 py-2 rounded-4xl text-sm"
            >
                <li>
                    <a href="#">Home</a>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Projects</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </div>
    </nav>
</template>

// src/components/Navbar.tsx
export default function Navbar() {
    return (
        <nav className="fixed w-full mx-auto mt-4">
            <div className="flex flex-row justify-center">
                <ul className="flex flex-row justify-center items-center backdrop-blur-lg rounded-4xl p-1 text-violet-200">
                    <li className="p-2">
                        <a
                            href="#about"
                            className="duration-100 hover:text-violet-100"
                        >
                            About
                        </a>
                    </li>
                    <li className="p-2">
                        <a
                            href="#skills"
                            className="duration-100 hover:text-violet-100"
                        >
                            Skills
                        </a>
                    </li>
                    <li className="p-2">
                        <a
                            href="#projects"
                            className="duration-100 hover:text-violet-100"
                        >
                            Projects
                        </a>
                    </li>
                    <li className="p-2">
                        <a
                            href="#contact"
                            className="duration-100 hover:text-violet-100"
                        >
                            Contact
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    )
}
